apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app-deploy
  namespace: nodejs-app
  labels:
    app: nodejs-app
spec:
  selector:
    matchLabels:
      app: nodejs-app
  replicas: 2
  template:
    metadata:
      labels:
        app: nodejs-app
    spec:
      containers:
        - name: nodejs-app
          image: oussamabs/node-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_USER
              value: "postgres"
            - name: DB_HOST
              value: "postgres-service"
            - name: DB_DATABASE
              value: "postgres_db"
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-password-secret
                  key: DB_PASSWORD
            - name: DB_PORT
              value: "5432"
          # resources:
          #   requests:
          #     memory: "256Mi"
          #   limits:
          #     memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app-service
  namespace: nodejs-app
  labels:
    app: nodejs-app
spec:
  selector:
    app: nodejs-app
  type: ClusterIP
  ports:
    - name: nodejs-app
      port: 8000
      targetPort: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nodejs-app-ingress
  namespace: nodejs-app
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: nodeapp.johnydev.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nodejs-app-service
                port:
                  number: 8000